# Generated by Django 4.0.8 on 2022-11-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housenumber',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housenumber',
            name='others',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housenumber',
            name='sqfeet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
