# Generated by Django 4.0.8 on 2022-11-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houseapp', '0002_housenumber_action_housenumber_others_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
